Update make

diff --git a/TheElement/makefile b/TheElement/makefile
--- a/TheElement/makefile
+++ b/TheElement/makefile
@@ -1,30 +1,20 @@
 ### MAIN VARIABLES
-GW=./gradlew
-ABC=../../../scripts/abc.sh
-ABC_CFG=../../../scripts/.abc-config
+GW=./gradlew --console plain
+ABC=../../scripts/abc.sh
+ABC_CFG=../../scripts/.abc-config
 # -Dabc.make.android.lifecycle.events.explicit
 # -Dabc.instrument.array.operations
 # -Dabc.instrument.debug -Dabc.instrument.multithreaded"
-JAVA_OPTS=" -Dabc.instrument.array.operations \
--Dabc.instrument.fields.operations \
--Dabc.taint.android.intents \
--Dabc.instrument.include=fifthelement.theelement"
+JAVA_OPTS=" -Dabc.instrument.array.operations -Dabc.instrument.fields.operations -Dabc.taint.android.intents -Dabc.instrument.include=fifthelement.theelement  -Dabc.instrument.multithreaded "
 
-# Skip instrumenting and calling this methods
 INSTRUMENTATION_OPTS=" \
---skip-package=fifthelement.theelement.persistence.hsqldb \
 --skip-class=fifthelement.theelement.R \
 --filter-package=java.io \
---filter-class=java.lang.StringBuilder"
-
-CARVING_JAVA_OPTIONS=" \
--Dorg.slf4j.simpleLogger.defaultLogLevel=info \
+--filter-class=java.lang.StringBuilder \
 "
 
 CARVING_OPTIONS=" \
---filter-method com.prismaqf.callblocker.rules.FilterRule.makeRegex \
---filter-method com.prismaqf.callblocker.rules.FilterRule.filterUnwanted \
---filter-method java.util.UUID.randomUUID \
+\
 "
 
 # Default
@@ -135,7 +125,8 @@ show :
 	$(info $(ADB))
 
 clean-gradle :
-	$(GW) clean
+	$(info "skip gradle clean")
+	$(GW) clean </dev/null
 
 list-sed:
 	@echo $(UNAME) -- $(SED)
@@ -156,6 +147,7 @@ clean-carved-tests :
 	$(RM) -rv app/src/allCarvedTest
 	$(RM) -rv app/src/carvedTest
 	$(RM) -rv .carved-all
+	$(RM) -rv carving.log
 	$(RM) -v carved-tests.log
 	$(RM) -v selected-carved-tests.log
 	$(RM) -v white-listed-tests.txt
@@ -176,7 +168,7 @@ clean-espresso-coverage :
 
 clean-all : clean-carved-tests clean-carved-coverage clean-espresso-coverage
 # Clean build files
-	$(GW) clean
+	$(GW) clean </dev/null
 # Clean up apk-related targets
 	$(RM) -v *.apk
 # Clean up all the logs
@@ -190,7 +182,7 @@ clean-all : clean-carved-tests clean-carved-coverage clean-espresso-coverage
 # Build the various apks
 app-original.apk : 
 	@export ABC_CONFIG=$(ABC_CFG) && \
-	$(GW) -PjacocoEnabled=false assembleDebug && \
+	$(GW) -PjacocoEnabled=false assembleDebug </dev/null && \
 	mv app/build/outputs/apk/debug/app-debug.apk app-debug.apk && \
 	$(ABC) sign-apk app-debug.apk && \
 	mv -v app-debug.apk app-original.apk
@@ -200,11 +192,12 @@ app-instrumented.apk : app-original.apk
 	export JAVA_OPTS=$(JAVA_OPTS) && \
 	export INSTRUMENTATION_OPTS=$(INSTRUMENTATION_OPTS) && \
 	INSTRUMENTED_APK=`$(ABC) instrument-apk app-original.apk` && \
+	$(ABC) instrument-apk app-original.apk && \
 	mv -v $${INSTRUMENTED_APK} app-instrumented.apk
 
 app-androidTest.apk :
 	@export ABC_CONFIG=$(ABC_CFG) && \
-	$(GW) assembleAndroidTest && \
+	$(GW) assembleAndroidTest </dev/null && \
 	mv app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk app-androidTest-unsigned.apk && \
 	$(ABC) sign-apk app-androidTest-unsigned.apk && \
 	mv -v app-androidTest-unsigned.apk app-androidTest.apk
@@ -212,7 +205,7 @@ app-androidTest.apk :
 ## the assembleAndroidTest task also builds the app if it starts from a clean build
 app-original-for-coverage.apk app-androidTest-for-coverage.apk:
 	@export ABC_CONFIG=$(ABC_CFG) && \
-	$(GW) -PjacocoEnabled=true clean assembleDebug assembleAndroidTest && \
+	$(GW) -PjacocoEnabled=true clean assembleDebug assembleAndroidTest </dev/null && \
 	mv app/build/outputs/apk/debug/app-debug.apk app-original-for-coverage.apk  && \
 	mv app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk app-androidTest-for-coverage.apk
 
@@ -244,7 +237,6 @@ carve-all : .carved-all
 .carved-all : $(ESPRESSO_TESTS)
 	@export ABC_CONFIG=$(ABC_CFG) && \
 	export CARVING_OPTIONS=$(CARVING_OPTIONS) && \
-	export CARVING_JAVA_OPTIONS=$(CARVING_JAVA_OPTIONS) && \
 	$(ABC) carve-all app-original.apk traces app/src/allCarvedTest force-clean 2>&1 | tee carving.log
 	@export ABC_CONFIG=$(ABC_CFG) && $(ABC) stop-all-emulators
 # Make sure this file has the right timestamp - probably touch will work the same
@@ -261,9 +253,9 @@ coverage-espresso-tests : espresso-tests-coverage/html/index.html
 espresso-tests-coverage/html/index.html : app-original-for-coverage.apk app-androidTest-for-coverage.apk
 # Ensure the right apk are installed and optionally start the emulator. Clean up the data if necessary.
 	$(call ensure_coverage_apks)
-	$(GW) -PjacocoEnabled=true -PcarvedTests=false clean jacocoGUITestCoverage 2>&1 | tee espresso-tests-coverage.log
+	$(GW) -PjacocoEnabled=true -PcarvedTests=false clean jacocoGUITestCoverage 2>&1 </dev/null | tee espresso-tests-coverage.log
 	$(RM) -r espresso-tests-coverage
-	mv -v app/build/reports/jacoco/jacocoGUITestCoverage espresso-tests-coverage
+	mv -v app/build/reports/jacoco/jacocoGUITestCoverage espresso-tests-coverage || echo "(Error: espresso-tests-coverage not found)"
 # This might not even be necessary
 	@export ABC_CONFIG=$(ABC_CFG) && $(ABC) stop-all-emulators
 
@@ -280,7 +272,7 @@ $(ESPRESSO_TESTS_COVERAGE): app-original-for-coverage.apk app-androidTest-for-co
 	$(eval COVERAGE_FOLDER := $(shell echo "$(@)" | sed -e 's|/html/index.html||'))
 # Execute the gradle target
 	@echo "Running Test $(TEST_NAME)"
-	$(GW) -PjacocoEnabled=true -PcarvedTests=false -Pandroid.testInstrumentationRunnerArguments.class=$(TEST_NAME) jacocoGUITestCoverage
+	$(GW) -PjacocoEnabled=true -PcarvedTests=false -Pandroid.testInstrumentationRunnerArguments.class=$(TEST_NAME) jacocoGUITestCoverage </dev/null
 	mv -v app/build/reports/jacoco/jacocoGUITestCoverage $(COVERAGE_FOLDER)
 # TODO debugAndroidTest folder might probably have some other name based on gradle config
 	mv -v app/build/outputs/code_coverage/debugAndroidTest/connected/*coverage.ec $(COVERAGE_FOLDER)/$(TEST_NAME).ec
@@ -289,7 +281,7 @@ coverage-unit-tests : unit-tests-coverage/html/index.html
 	@echo "Done"
 
 unit-tests-coverage/html/index.html :
-	$(GW) -PjacocoEnabled=true -PcarvedTests=false clean jacocoUnitTestCoverage 2>&1 | tee unit-tests-coverage.log
+	$(GW) -PjacocoEnabled=true -PcarvedTests=false clean jacocoUnitTestCoverage 2>&1 </dev/null | tee unit-tests-coverage.log
 	$(RM) -r unit-tests-coverage
 	mv -v app/build/reports/jacoco/jacocoUnitTestCoverage unit-tests-coverage
 
@@ -305,9 +297,9 @@ all-carved-tests-coverage/html/index.html : carved-tests.log
 carved-tests.log : .carved-all
 	$(RM) -r app/src/carvedTest
 	cp -r app/src/allCarvedTest app/src/carvedTest
-	$(GW) -PjacocoEnabled=true -PcarvedTests=true clean jacocoUnitTestCoverage 2>&1 | tee carved-tests.log
+	$(GW) -PjacocoEnabled=true -PcarvedTests=true clean jacocoUnitTestCoverage 2>&1 </dev/null | tee carved-tests.log
 	$(RM) -r all-carved-tests-coverage
-	mv -v build/carvedTest/coverage all-carved-tests-coverage
+	mv -v build/carvedTest/coverage all-carved-tests-coverage || echo "(Error: all-carved-tests-coverage not found)"
 
 # This is required because we need it to run each carved test in isolation
 selected-carved-tests-coverage/html/index.html : selected-carved-tests.done
@@ -317,9 +309,9 @@ endif
 # Ensure we are using the right carved tests by creating a link to the folder.
 	$(RM) -r app/src/carvedTest
 	cp -r app/src/selectedCarvedTest app/src/carvedTest
-	$(GW) -PjacocoEnabled=true -PcarvedTests=true clean jacocoUnitTestCoverage 2>&1 | tee selected-carved-tests.log
+	$(GW) -PjacocoEnabled=true -PcarvedTests=true clean jacocoUnitTestCoverage 2>&1 </dev/null | tee selected-carved-tests.log
 	$(RM) -r selected-carved-tests-coverage
-	mv -v build/carvedTest/coverage selected-carved-tests-coverage
+	mv -v build/carvedTest/coverage selected-carved-tests-coverage || echo "(Error: selected-carved-tests-coverage not found)"
 
 $(CARVED_TESTS_COVERAGE): carved-tests.log
 # Ensure we use all the carvedTests here
@@ -331,9 +323,9 @@ $(CARVED_TESTS_COVERAGE): carved-tests.log
 # Clean up the coverage folder (this should not be necessary)
 	$(RM) -rv $(COVERAGE_FOLDER)
 # Run the single unit test and collect coverage
-	$(GW) -PjacocoEnabled=true -PcarvedTests=true -PcarvedTestsFilter=$(TEST_NAME) clean jacocoUnitTestCoverage
+	$(GW) -PjacocoEnabled=true -PcarvedTests=true -PcarvedTestsFilter=$(TEST_NAME) clean jacocoUnitTestCoverage </dev/null
 # Copy the coverage folder in the expected place
-	mv -v ./build/carvedTest/coverage $(COVERAGE_FOLDER)
+	mv -v ./build/carvedTest/coverage $(COVERAGE_FOLDER) || echo "(Error: ./build/carvedTest/coverage not found)"
 
 coverage-for-each-carved-test : carved-tests.log $(CARVED_TESTS_COVERAGE)
 ifeq ($(REQUIRE_RERUN), 1)
